---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${service.name}
  namespace: ${solution.name}
data:
  postgres.host: ${postgres.host}
  postgres.port: ${postgres.port}
  postgres.dbname: ${postgresdbname}
  postgres.schema: ${postgres.schema}
  schema: ${schema.location}
  otel.otlpExporterEndpoint: ${otel.otlpExporterEndpoint}
